### ISSUE TITLE
Exclude patterns in array.

### ISSUE THREAD

**Issue by Bartmax** [brunch/brunch#1029]
I see that there was an addition on anymatch https://github.com/es128/anymatch/issues/6 for this scenario, but I couldn't make it to work with brunch 1.8.5, is this supposed to work?

```
  files:
    javascripts:
      joinTo: 
         'js/libs.js': ['bower_components/jquery/dist/**/*.js', '!*.js']
```

**Comment by es128** [comment]
What are you trying to do with those two globs? Doesn't seem like the second one with the negation would have any effect.

**Comment by Bartmax** [comment]
Well, yes sorry, that example is kinda non-sense.
I will try to give the 'real' example of what I'm trying to accomplish.

```
  files:
    javascripts:
      joinTo: 
        'js/app.js' : /^app/
        'js/jquery.js': 'bower_components/jquery/dist/**/*.js'
        'js/bootstrap.js': 'bower_components/bootstrap/**/*.js'
        'js/libs.js': [/^vendor/, '!bower_components/jquery/**/*', '!bower_components/bootstrap/**/*']
```
 
all I want to do is exclude jquery and bootstrap from concat, i need those to have it on it's own file.
