### ISSUE TITLE
JS code into Css when use NPM

### ISSUE THREAD

**Issue by julienbrument** [brunch/brunch#1073]
Hi guys,

I have an issue when I use npm packages with brunch, that's adding a javascript code to my css file.

I use:
OS: OS X 10.10.5,
Node: 4.0.0,
Brunch: 2.0.4

My brunch-config: 
```javascript
    npm:{

		enabled:true,
		packages:['jquery', 'page', 'bootstrap'],
		
		globals: {
			jQuery: 'jquery'
		}

	},

	paths: {
		watched:['front_src']
	},

	files: {

		javascripts: { joinTo: 'js/app.js'  },
		stylesheets: {

			joinTo: {
				'css/app.css': 'front_src/css/app.bundle.scss'
			}
		}
	},

	plugins: {

		sass: {
			debug:true
		},

		browserSync: {
			notify:false
		}


	}
```

Css output file: 
```css
...
/* line 2, /Users/giul/workspace/pedisystems/front_src/css/style/_contact.scss */
.contact {
  position: relative;}
  /* line 8, /Users/giul/workspace/pedisystems/front_src/css/style/_contact.scss */
  .contact .btn {
    border-radius: 100px; }

/* line 2, /Users/giul/workspace/pedisystems/front_src/css/style/_footer.scss */
.footer {
  line-height: 2; }

(function() {
    var global = window;
    var __shims = {assert: ({}),buffer: ({}),child_process: ({}),cluster: ({}),crypto: ({}),dgram: ({}),dns: ({}),events: ({}),fs: ({}),http: ({}),https: ({}),net: ({}),os: ({}),path: ({}),punycode: ({}),querystring: ({}),readline: ({}),repl: ({}),string_decoder: ({}),tls: ({}),tty: ({}),url: ({}),util: ({}),vm: ({}),zlib: ({}),process: ({"env":{}})};
    var process = __shims.process;

    var __makeRequire = function(r, __brmap) {
      return function(name) {
        if (__brmap[name] !== undefined) name = __brmap[name];
        name = name.replace(".js", "");
        return ["assert","buffer","child_process","cluster","crypto","dgram","dns","events","fs","http","https","net","os","path","punycode","querystring","readline","repl","string_decoder","tls","tty","url","util","vm","zlib","process"].indexOf(name) !== -1 ? __shims[name] :  r(name);
      }
    };
  })();window.jQuery = require('jquery');
/*# sourceMappingURL=app.css.map*/
```

If npm is disabled, works like a charm. I made a mistake somewhere ? or unexpected behavior ? 

Thank's for this amazing tool.
