### ISSUE TITLE
browsersync, autoreload with brunch and jade - have to reload twice before seeing changes?

### ISSUE THREAD

**Issue by alancwoo** [brunch/brunch#1268]
### Description

In a simple [brunch](http://brunch.io) project, I have tried using both browsersync and autoreload to keep my browser updated automatically with changes.

Edits to javascript and css are immediately updated, but when updating a jade template, the browser performs a reload, but I have to save again or manually reload the browser to see the change.

It's strange because according to the debug output, it seems to do two reloads, and also copy the html before the second reload.

**On change to jade template and save:**

    brunch:file-list Reading 'app/index.jade' +7s
      brunch:watch File 'app/index.jade' received event 'change' +0ms
      brunch:pipeline Compiling 'app/index.jade' with 'JadeCompiler' +0ms
      brunch:pipeline getDependencies 'app/index.jade' with 'JadeCompiler' +2ms
      brunch:file-list Compiled file 'app/index.jade'... +1ms
      brunch:write Writing 1/4 files +65ms
      brunch:generate Concatenating app/index.jade, app/js/app.js to public/app.js +0ms
      brunch:common Writing file 'public/app.js' +1ms
    23 Feb 16:11:04 - info: compiled index.jade and 1 cached file into app.js in 70ms
    [BS] Reloading Browsers...
      brunch:watch File 'app/assets/index.html' received event 'change' +32ms
      brunch:file-list Copied asset 'app/assets/index.html' +1ms
      brunch:file-list Copied asset 'app/assets/index.html' +0ms
      brunch:write Writing 0/4 files +67ms
    23 Feb 16:11:04 - info: copied index.html in 69ms
    [BS] Reloading Browsers...

### Environment

1. Brunch: 1.8.5
2. Node: 5.4.0
3. NPM: 3.3.12
4. Operating system: OS X 10.11.3

### `package.json` contents

```
{
  "name": "brunch-jade-test",
  "version": "0.0.1",
  "description": "brunch-jade-test",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "brunch": "^1.8.5",
    "css-brunch": "^1.7.0",
    "jade-brunch": "^1.8.1",
    "javascript-brunch": "^1.8.0",
    "static-jade-brunch": "^1.8.0",
    "stylus": "^0.53.0",
    "stylus-brunch": "^1.8.1"
  },
  "dependencies": {
    "autoprefixer": "^6.3.3",
    "browser-sync-brunch": "0.0.9",
    "postcss-brunch": "^0.5.0"
  }
}
```

### brunch config contents

```
module.exports = config:
  files:
    javascripts: joinTo:
      'vendor.js': /^(?!app\/)/
      'app.js': /^app\//
    stylesheets: joinTo:
      'vendor.css': /^(bower_components|vendor)/
      'app.css': /^app\//
    templates: joinTo:
      'app.js': /.+\.jade$/
  modules:
    wrapper: false
    definition: false
  plugins:
    browserSync:
      notify: false
    postcss:
      processors: [
        require('autoprefixer')(['last 8 versions'])
      ]

```

### Other useful files, when present (`bower.json` etc.)

Originally I asked this question on Stackoverflow but @goshakkk mentioned it should be in the issues instead, my apologies for the delay getting this here. I've made a sample project and zipped everything [here](http://d.pr/f/1fHC3/5cvVDa7c).

If you try (after bower, npm install) `brunch w -d --server`, then edit `app/index.jade`, changes are not automatically reloaded. Or is this intended behaviour? (even though browsersync says reloading browser)
