### ISSUE TITLE
brunch@2.6.x throws TypeError during build

### ISSUE THREAD

**Issue by wekyle** [brunch/brunch#1290]
### Description

When running build with `brunch@2.6.5` on my CI box, the build fails as follows:

```
ubuntu@box516:~/[redacted]$ ./node_modules/brunch/bin/brunch b
11 Apr 23:35:24 - error: [TypeError: Cannot read property 'indexOf' of undefined] 
11 Apr 23:35:27 - info: compiled 126 files and 5 cached into 3 files, copied 120 in 2.9 sec
```

I then installed `brunch@2.5.0` to confirm my suspicion that this was a version-specific issue:

```
ubuntu@box516:~/[redacted]$ npm i brunch@2.5.0
```

... and then ran build again:

```
ubuntu@box516:~/[redacted]$ ./node_modules/brunch/bin/brunch b
11 Apr 23:36:25 - warn: bower_components/angularUtils-pagination/dirPagination.tpl.html compiled, but not written. Check your templates.joinTo config
11 Apr 23:36:26 - info: compiling
11 Apr 23:36:27 - info: compiled 36 files into 3 files, copied 51 in 5 sec
11 Apr 23:36:29 - info: compiled 126 files and 5 cached into 3 files, copied 120 in 2.8 sec
```

### Environment

1. Brunch: `2.6.5` and `2.5.0`
2. Node: `4.2.1`
3. NPM: `3.8.6`
4. Operating system: Ubuntu 12.04

### brunch config contents

```
jspath = /client\/.*\.js$/

exports.config =
  modules:
    definition: false
    wrapper: false
  paths:
    'root': '.'
    'public': 'dist'
    'watched': ['client']
  files:
    javascripts:
      joinTo:
        'js/app.js': [
          jspath
          '!client/**/*.spec.js'
        ]
        'js/vendor.js': [
          '/client/vendor'
          /bower_components/
        ]
      order:
        before: [
          'bower_components/jquery/jquery.js'
          'bower_components/angular/angular.js'
          'client/app/constants.js'
          'client/app/app.js'
        ]
    stylesheets:
      joinTo:
        'css/app.css': [
          /client\/app\/styles/
        ]
        'css/vendor.css': /bower_components/
    templates:
      joinTo:
        'js/templates.js': /client\/(app|components)/
  plugins:
    angular_templates:
      path_transform: (s) -> s.replace('client/','')
    ng_annotate:
      pattern: ['app/']
    babel:
      presets: ['es2015']
      ignore: [
        /^(bower_components|vendor)/
      ]
      pattern: jspath
    uglify:
      drop_console: true
    postcss:
      processors: [
        require('autoprefixer')(['last 8 versions'])
      ]
    browserSync:
      https: true
      injectChanges: true
      background: true
      ui:
        port: 8080
  server: port: 3333
  npm:
    enabled: false
  conventions:
    assets: /client(\\|\/)assets(\\|\/)/
    vendor: 'bower_components/'
    ignored: [
      /[\\/]_/,
      /vendor[\\/]node[\\/]/,
      '**/*.spec.js'
    ]
  sourceMaps: true
  overrides:
    production:
      optimize: true
      sourceMaps: false
      plugins:
        autoReload:
          enabled: false
```

### Notes

I ran a build in debug mode in `2.6.5`, and it didn't provide anything of value: the error was logged without a stack trace, and surrounded by `brunch:watch` and `brunch:list` debugs for CSS files.

It should also be noted that the issue does not crop up in `brunch@2.6.5` on my MacBook Pro, OS X 10.11.2.

I'm omitting my package files since this issue is in a production codebase.
