### ISSUE TITLE
Bower.js error is not clear enough

### ISSUE THREAD

**Issue by jouana** [brunch/brunch#1563]
Hi all,

### Contexte

I'm on a project with many legacy and we make a decision with my teammates to migrate slowly towards es2015+ with babel.

Today our build is made with Grunt and I want to get this opportunity to replace this by brunch.

But we have some constraint like no wrapping and no npm because of legacy.

If I can finalise this part then we'll be able to start our migration.

### Description

We want to make a bundle vendor with all bower dependencies but in our contexte nothing happen

### Expected behavior

When a vendor.js is declared in brunch config with target onbower_components a file public/vendor.js must be build.

### Actual behavior

Nothing happen

### Environment

1. Brunch: 2.9.1
2. Node: 6.9.1
3. NPM: 3.10.8
4. Operating system: Linux debian 64x

### `package.json` contents

```
{
  "name": "xxx",
  "private": "true",
  "version": "0.0.1",
  "dependencies": {},
  "repository": {},
  "scripts": {
    "postinstall": "bower install && brunch b",
    "start": "brunch watch --server --port 9000",
    "build": "brunch build -d"
  },
  "devDependencies": {
    "bower": "^1.8.0",
    "babel-brunch": "^6.0.6",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-es2016": "^6.16.0",
    "bootstrap-sass": "^3.3.7",
    "brunch": "^2.9.1",
    "jasmine-core": "*",
    "jasminewd": "^1.1.0",
    "javascript-brunch": "^2.0.0",
    "jshint-stylish": "^1.0.0",
    "karma": "^0.13.22",
    "karma-coverage": "^0.3.1",
    "karma-jasmine": "^0.3.5",
    "karma-junit-reporter": "^0.2.2",
    "karma-ng-html2js-preprocessor": "^0.2.0",
    "karma-phantomjs-launcher": "^1.0.0",
    "phantomjs-prebuilt": "^2.1.3",
    "protractor": "^2.1.0",
    "sass-brunch": "^2.7.0"
  }
}
```

### brunch config contents

```
module.exports = config:
  files:
    javascripts:
      joinTo:
        'vendor.js': /^bower_components/
        'app.js': /^app/
    stylesheets:
      joinTo:
        'styles.css': 'app/styles/main.scss'
  npm:
    enabled: false
  modules:
    wrapper: false
    definition: false
  conventions:
    assets: /^app(\\|\/)assets/
    ignored: /^test/
  plugins:
    sass:
      options:
        includePaths: ['node_modules/bootstrap-sass/assets/stylesheets']
    babel:
      presets: ['es2015']
      pattern: /^.js$/
  hooks:
    onCompile: (file, changedAssets) => console.log(file.map((f) => f.path))
```

### Bower config content

```
{
  "name": "xxx",
  "version": "0.0.1",
  "dependencies": {
    "angular": "1.5.5",
    "jquery": "2.2.3",
    "moment": "2.13.0",
    "bootstrap": "3.3.4",
    "angular-cookies": "1.5.5",
    "angular-resource": "1.5.5",
    "angular-sanitize": "1.5.5",
    "angular-ui-router": "0.2.18",
    "angular-bootstrap": "0.14.3",
    "angular-mocks": "1.5.5",
    "angular-loading-bar": "0.9.0",
    "font-awesome": "4.3.0",
    "angular-smart-table": "2.1.8",
    "ng-table": "1.0.0-beta.9",
    "angular-breadcrumb": "0.4.1",
    "lodash": "4.12.0",
    "lodash-mix": "0.0.8",
    "ng-csv": "0.3.6",
    "angular-toggle-switch": "angular-bootstrap-toggle-switch#0.5.6",
    "angular-ui-notification": "0.2.0",
    "angular-mask": "3.0.16",
    "jquery.maskedinput": "1.4.1",
    "ng-iban": "0.9.0",
    "ui-select": "angular-ui-select#0.14.9",
    "ng-stomp": "0.0.2",
    "css-toggle-switch": "4.0.2",
    "angular-ui-sortable": "0.14.0",
    "angular-tooltips": "1.1.4",
    "async": "^1.5.2",
    "myforce-angularjs-dropdown-multiselect": "^1.10.2"
  }
}
```

Sorry for my english,
Regards.
