### ISSUE TITLE
Split vendor.js

### ISSUE THREAD

**Issue by meneerprins** [brunch/brunch#1753]
### Description

Might not be an issue, but I would like to know if it's possible to get multiple vendor.js files if you use brunch for a project that has multiple websites. The project I'm working on is a Rails app with brunch and has 3 websites, 2 public sites with different domains (jobseeker and employer) and an admin panel. 

### Current behavior

In de current situation the javascript libraries from NPM that are only used in employer.js (via es6 import) are also used by jobseeker.js which isn't exactly good for the pagespeed (vendor.js is 1mb!).

Example: 
- employer website: uses flickity.js for a slider
- jobseeker website: uses swiper.js for a slider
- vendor.js: has both libraries imported

### Expected behavior

It would be nice if it's possible to get 3 vendor.js files (or just the npm libraries in the jobseeker.js, employer.js and admin.js without vendor.js) so every website has only the js libraries imported that are used.

### Environment

1. Brunch: 2.10.10
1. Node.js: latest
1. NPM: 5.4.2
1. Operating system: MacOS High Sierra
1. Code editor: Atom

### partial brunch config contents

```
module.exports =
  files:
    javascripts:
      joinTo:
        'admin.js': /^app\/frontend\/admin\/js\//
        'employer.js': /^app\/frontend\/employer\/js\//
        'jobseeker.js': /^app\/frontend\/jobseeker\/js\//
        'vendor.js': /^(?!app\/frontend\/admin\/js|app\/frontend\/employer\/js|app\/frontend\/jobseeker\/js)/
    stylesheets:
      joinTo:
        'admin.css': /^app\/frontend\/admin\/css\//
        'employer.css': /^app\/frontend\/employer\/css\//
        'jobseeker.css': /^app\/frontend\/jobseeker\/css\//
    templates:
      joinTo: 'app.js'
```
