### ISSUE TITLE
vendor.js won't compile

### ISSUE THREAD

**Issue by ghost** [brunch/brunch#334]
I have no idea why javascript/vendor.js won't get compiled.

Here is my config.coffee:

```
exports.config =
  # See http://brunch.readthedocs.org/en/latest/config.html for documentation.
  files:
    javascripts:
      defaultExtension: "ls"
      joinTo:
        "javascripts/app.js": /^app/
        "javascripts/vendor.js": /^vendor/
        "test/javascripts/test.js": /^test(\/|\\)(?!vendor)/
        "test/javascripts/test-vendor.js": /^test(\/|\\)(?=vendor)/
      order:
        before: [
          "vendor/scripts/prelude-min.js",
          "vendor/scripts/stativus.js",
          "vendor/scripts/sugar.min.js"
        ]

    stylesheets:
      defaultExtension: "scss"
      joinTo:
        "stylesheets/app.css": /^(app|vendor)/
        "test/stylesheets/test.css": /^test/

    templates:
      defaultExtension: "hbs"
      joinTo: "javascripts/app.js"
```

All other files:

/javascripts/app.js
/stylesheets/app.css

i created but not /javascripts/vendor.js.

Any clue?
