### ISSUE TITLE
plugin include file not loaded if vendor regex is changed

### ISSUE THREAD

**Issue by rashfael** [brunch/brunch#419]
If I move the vendor directory inside the app directory and configure brunch like this:

```
 paths:
      vendor: 'app/vendor/'
 files:
      javascripts:
          joinTo:
              'javascripts/vendor.js': /^app(\/|\\)vendor/
```

the plugin includes (namely the jade runtime.js) are not compiled into the vendor.js.

As a workaround we changed the regex for the vendor.js file to:

```
/vendor(\/|\\)/
```

It is not really obvious that this regex is related to how the plugin include files are built.
