### ISSUE TITLE
server.coffee isn't watched for changes

### ISSUE THREAD

**Issue by jerfowler** [brunch/brunch#494]
When you specify a `server.coffee` in the config, brunch doesn't bother to watch for changes and restart. Would like for brunch to monitor server.coffee as well as any additional locations specified in the config file.

```
server:
    path: 'server.coffee'
    watch: ['routes', 'lib']
    port: 3333
    base: '/'
    run: yes
```
