### ISSUE TITLE
1.6.x does not require test modules

### ISSUE THREAD

**Issue by jonbuffington** [brunch/brunch#530]
In brunch 1.5.x, each test module would be required in the generated `test.js` file allowing the test cases to be executed when loaded in a browser. In 1.6.x, brunch does not require test modules. Is this an omission or a change in generating concatenated unit tests scripts?

```
  files:
    javascripts:
      joinTo:
        'scripts/app.js': /^app/
        'scripts/vendor.js': /^vendor/
        'test/scripts/test.js': /^test(\/|\\)(?!vendor)/
        'test/scripts/test-vendor.js': /^test(\/|\\)(?=vendor)/
```
