### ISSUE TITLE
Bower support for all components.

### ISSUE THREAD

**Issue by Ni0rd** [brunch/brunch#588]
I have a project with components that doesn't support the main property and/or with deprecated component.json file.
At this moment, the read-component emit an error:

```
Bower component bower.json must have `main` property. Contact component author of "components/backbone"
```

If a component doesn't match the brunch requirements, how can it be consumed?
I don't think it should break the build process, maybe only a warning?

What about an extra config setting to make the components fit (like a merge off the bower.json or the deprecated component.json file):

```
config:
  bower:
    backbone: 
      main: 'backbone.js'
```

This could be interesting also for components with multiple builds like Lodash to override default export:

```
config:
  bower:
    lodash: 
      main: './dist/lodash.mobile.js'
```

Maybe also let the possibility to disable Bower integration:

```
config:
  bower: false
```
