### ISSUE TITLE
Custom wrapper function pulls in scripts in `node_modules/../vendor`

### ISSUE THREAD

**Issue by wprater** [brunch/brunch#695]
With the defaults file paths in `node_modules` that match `vendor` are not concatenated into my `joinTo`s.  However, when I have a custom method, they are. Maybe I've set it up incorrectly.

My app lives in `src/app`.

```
    javascripts:
      joinTo:
        'js/app.js': /^src(\/|\\)(app|common|lib)/
        'js/lib.js': /^src(\/|\\)lib/
        'js/vendor.js': /^(bower_components|vendor(\/|\\)scripts)/
```

```
    wrapper: (path, data, isVendor) ->
      # FIXME files in node_modules that match vendor are being concat.
      # return if path.match('node_modules/')?

      # js in app or common should be wrapped in module pattern.
      if path.match('src/app/')? or
      path.match('src/common/')?
        """
        (function() {
          'use strict';
          // #{path}

          #{data}
        }).call(this);\n\n
        """
      # vendor and everything else just output file.
      else
        """
        \n\n// #{path}
        #{data}
        """
```
