### ISSUE TITLE
Custom arguments and deployment workflow

### ISSUE THREAD

**Issue by simonrenoult** [brunch/brunch#777]
Hi,

Is there any way to specify custom arguments to the brunch client ? Indeed, I would like to specify my app to use dev urls (eg: `localhost:3333/static`) when I'm developing and production urls when deploying (eg: `myaccount.github.io/static`).

Currently, I manage this through `coffee` and `less` variables like this: 

```
conf =
        env: 'dev'
        deployment:
            dev:  'http://localhost:3334/static'
            prod: 'http://myaccount.everplaces.com/static'
```

and

```
@dev: 'http://localhost:3334/static';
@test: 'http://myaccount.everplaces.com/static/';
@env: @dev;
```

Every time I build, I manually switches the environment, however this is painful. Any way to simplify this workflow with brunch (using process.argv or something similar for example) ?
