### ISSUE TITLE
config.paths.watched doesn't  watch files

### ISSUE THREAD

**Issue by viktoraseev** [brunch/brunch#843]
My project have one file that sit in the project root folder. I need to watch on it and copy to public folder on change.

Since this is root folder, I can't setup watch on it, this will be too slow. So i decided to put this file to watched option:
```
exports.config =
  paths:
      public: 'public'
      watched: ['app', 'thisFileNeedsToBeWatched.htm']
```
Unfortunately, that doesn't work, brunch will not watch for this particular file.

This happens because watch.js:139 is setup to ignore some files:
```
      params = {
        ignored: fs_utils.ignored,
```

where fs_utils.ignored (fs_utils.js\common.js:47) use this regexp to determine which files/folders should be ignored: 
```
    re1 = /\.(?!htaccess|rewrite)/;
```
I think that regexp is incorrect because it does ignore all files that have dot in their name. 
Correct one may be 
```
    re1 = /^\.(?!htaccess|rewrite)/;
```
