### ISSUE TITLE
One file from bower_components is not concatenated to vendor.js file

### ISSUE THREAD

**Issue by alekbarszczewski** [brunch/brunch#893]
I have encountered strange issue. When I build my app locally (on mac) everything is fine, however when I build app on CI servers (codeship.io, ubuntu) for some reason one of the modules in bower_components is not concatenated into vendor.js (All others are concatenated correctly). I haved checked it and this module is there in bower_components directory after `bower install` and before `brunch b -P` commands. The name of the module is `jQuery.serializeObject`.

Here is my **bower.json**:

```
{
  "name": "myapp",
  "version": "0.1.0",
  "main": "public/javascripts/app.js",
  "dependencies": {
    "chaplin": "~1.0.0",
    "console-polyfill": "~0.1.0",
    "lodash": "~2.4.0",
    "jquery": "~2.0.2",
    "normalize-css": "~2.1.2",
    "jQuery.serializeObject": "~2.0.3",
    "h5bp-helpers": "~0.1.0"
  },
  "overrides": {
    "backbone": {
      "dependencies": {
        "lodash": "*",
        "jquery": "*"
      },
      "main": "backbone.js"
    }
  }
}

```
and **brunch_config.coffee**:
```
exports.config =
  files:
    javascripts:
      joinTo:
        'javascripts/app.js': /^app/
        'javascripts/vendor.js': /^(vendor|bower_components)/

    stylesheets:
      joinTo: 'stylesheets/app.css'

    templates:
      joinTo: 'javascripts/app.js'
```

This is very strange as I am using same build script as on local machine, there is no warning on `brunch b -P` command, everything is fine, app is even works, except that `jQuery.serializeObject` is not included in `vendor.js` for some reason (app works until it tries to invoke `$.serializeObject`).

Any ideas why this is happening? 
Is there any "debug" mode in brunch to see exactly which files are concatenated and where?

p.s.

I love brunch, I am using it in every project in company I work :)

**Comment by es128** [comment]
Closing due to lack of feedback.

**Comment by jjalonso** [comment]
Same here, compile everything but no vendor.js (bower_components)

exports.config =
  # See http://brunch.io/#documentation for docs.
  files:
    javascripts:
      joinTo:
        'app.js': /^app/
        'vendor.js': /^(bower_components|vendor)/
    stylesheets:
      joinTo: 'app.css'
    templates:
      joinTo: 'app.js'

**Comment by yagudaev** [comment]
same issue just happen to me with `bootstrap.js`.

```
exports.config =
  # @see http://brunch.io/#documentation for docs
  files:
    javascripts:
      joinTo:
        'scripts/app.js': /^app/
        'scripts/vendor.js': /^(?!app)/
    stylesheets:
      joinTo:
        'styles/app.css': /^app\/styles\/app.scss/
        'styles/vendor.css': /^(bower_components|vendor)/
    templates:
      joinTo: 'scripts/app.js'

  modules:
    nameCleaner: (path) ->
      path
        # Strip the app/ and .cjsx extension from module names
        .replace(/app\//, '')
        .replace(/\.cjsx/, '')

  paths:
    watched: ['app', 'vendor']

  plugins:
    # react:
    #   harmony: yes # include es6 transforms
    coffeelint:
      pattern: /^app\/.*\.coffee$/
      options:
        max_line_length: {level: 'ignore'}

    sass:
      mode: 'ruby'
      options:
        includePaths: [
          'bower_components/bootstrap-sass/assets/stylesheets'
          'bower_components/bootstrap-offcanvas/src/sass'
        ]

    assetsmanager:
      copyTo:
        'fake_api/': ['spec/fixtures/requests/*']
```

The file just appears to be copied down to `/public/javascripts/bootstrap.js`. Where as all other files are in `/public/scripts/vendor.js`
