### ISSUE TITLE
Exclude packages from concatenating.

### ISSUE THREAD

**Issue by Bartmax** [brunch/brunch#961]
This is what I want to achieve:

from bower_components, I want to concat all js files into libs.js but I want some 'package' to have it's own file, not concatenated so I can use a cdn with a fallback.

this is my working config:

```
    files:
        javascripts:
          joinTo:
            'scripts/app.js': /^app/
            'scripts/jquery.js': 'bower_components/jquery/**/*.js'
            'scripts/bootstrap.js': 'bower_components/bootstrap/**/*.js'
            'scripts/lib.js': /^(vendor|bower_components)(\/|\\)(?!jquery\\|bootstrap\\|.*\.min\.js)/
```

this was confusing and tedious. couldn't be a way that if brunch find the file in the stack it doesn't include it on the others (maybe an option) so I do not need to exclude already added files

also ideally, with the ability to ignore the min files, afaik conventions/ignored only works on folders.

I can't think of a scenario where you want the same file in multiple destinations (but I might be wrong) so that being an option works.

Proposal: 
```
    files:
        javascripts:
          exclude: '/**/*.min.js'
          joinOnce: true
          joinTo:
            'scripts/app.js': /^app/
            'scripts/jquery.js': 'bower_components/jquery/**/*.js'
            'scripts/bootstrap.js': 'bower_components/bootstrap/**/*.js'
            'scripts/lib.js': /^(vendor|bower_components)/
```
