### ISSUE TITLE
Review harder use-cases for NPM integration

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#963]
E.g. backbone, react, exim

**Comment by chrismcv** [comment]
you maybe know this already, but react is problematic presently....

using the simple skeleton and adding index.cjsx (with coffee-react-brunch package installed)
```
React = require 'react'

Something = React.createClass
  render: ->
    <span>Hi</span>

React.render(<Something />, document.body)
```
fails with `TypeError: React.createClass is not a function`

```
require('react')
app.js:5198 function (condition, format, a, b, c, d, e, f) {
  if ("production" !== process.env.NODE_ENV) {
    if (format === undefined) {
      throw new Error('invariant requires an error message argument');
    }
  }

  if (!condition) {
    var error;
    if (format === undefined) {
      error = new Error(
        'Minified exception occurred; use the non-minified dev environment ' +
        'for the full error message and additional helpful warnings.'
      );
    } else {
      var args = [a, b, c, d, e, f];
      var argIndex = 0;
      error = new Error(
        'Invariant Violation: ' +
        format.replace(/%s/g, function() { return args[argIndex++]; })
      );
    }

    error.framesToPop = 1; // we don't care about invariant's own frame
    throw error;
  }
}
```

**Comment by nezoomie** [comment]
Not sure if helpful, anyways I'm currently having problems with backbone and backbone.radio. I always get `Uncaught Error: Cannot find module "backbone"`. For some reason they both get registered as `underscore` into vendor.js:

```
require.register('underscore', function (exp, req, mod) {
// ...
```

in my package.json:

```
  "dependencies": {
    "javascript-brunch": ">= 1.0 < 1.9",
    "css-brunch": ">= 1.0 < 1.9",
    "uglify-js-brunch": ">= 1.0 < 1.9",
    "clean-css-brunch": ">= 1.0 < 1.9",
    "brunch": "~1.8.2",
    "react-brunch": "~1.0.9",
    "stylus-brunch": "~1.8.1",
    "backbone": "~1.1.2",
    "backbone.radio": "~0.9.0",
    "js-logger": "~0.9.14",
    "react": "~0.13.2",
    "lodash": "~3.8.0"
  }
```
(removed underscore.js dependency to check if it was an issue, doesn't make any difference)

my brunch-config.coffee:

```
exports.config =
  # See https://github.com/brunch/brunch/blob/master/docs/config.md for documentation.
  paths:
    public: 'public'

  files:
    javascripts:
      joinTo:
        'javascripts/app.js': /^app/
        'javascripts/vendor.js': /^(vendor|bower_components|node_modules)/
        'test/javascripts/app-test.js': /^test(\/|\\)(?!vendor)/
        'test/javascripts/vendor-test.js': /^test(\/|\\)(?=vendor)/

    stylesheets:
      joinTo:
        'stylesheets/app.css': /^(app|vendor)/
        'test/stylesheets/app-test.css': /^test/
      order:
        before: []
        after: []

    templates:
      joinTo: "javascripts/app.js"

  conventions:
    assets: /(assets|vendor\/assets|font)/

  npm:
    enabled: true

```

brunch v1.8.2, node v0.12.1
