### ISSUE TITLE
the watcher compiles a changed file as an empty file

### ISSUE THREAD

**Issue by maxlath** [brunch/brunch#971]
I'm having this weird, exhausting issue since a few weeks.
The pattern seems to be this one: when I edit a file, around 1/10 of the times the file updated just before is compiled as empty.

Brunch shows no error, I got to detect the error from `ReferenceErrors` and alikes (when it's an empty js module) or missing DOM elements (when it's an empty handlebars template) that show up as the module is empty, getting me paranoid on every error: "is that coming from my code or from this random f*** bug?". I generally solve it by re-editing the empty file to force it to be recompiled.

The logs don't seem to show anyting (debug mode):
```
12 May 14:40:27 - info: compiled initialize.coffee and 328 cached files into app.js in 1271ms
  brunch:file-list Reading 'app/modules/comments/comments.coffee' +28s
  brunch:watch File 'app/modules/comments/comments.coffee' received event 'change' +0ms
  brunch:pipeline Compiling 'app/modules/comments/comments.coffee' with 'CoffeeScriptCompiler' +1ms
  brunch:helpers Wrapping '"modules/comments/comments"' with commonjs +20ms
  brunch:source-file Generated source map for 'app/modules/comments/comments.coffee'  +0ms
  brunch:file-list Compiled file 'app/modules/comments/comments.coffee'... +6ms
  brunch:write Writing 1/4 files +72ms
  brunch:generate Concatenating [some files], app/initialize.coffee, [LOTS of files] to public/javascripts/app.js +375ms
  brunch:common Writing file 'public/javascripts/app.js' +363ms
  brunch:common Writing file 'public/javascripts/app.js.map' +290ms
12 May 14:40:56 - info: compiled comments.coffee and 328 cached files into app.js in 1134ms
```
and as a result I get
```
;require.register("initialize", function(exports, require, module) {

});
```
instead of 
```
;require.register("initialize", function(exports, require, module) {
   [my module code here]
});
```

Here is my config file:
```
exports.config =
  notifications: yes
  sourceMaps: true
  files:
    javascripts:
      defaultExtension: "coffee"
      joinTo:
        'javascripts/vendor.js': /^(vendor\/scripts|bower_components)/
        'javascripts/app.js': /^app/
      order:
        before: [
          "bower_components/jquery/dist/jquery.js"
          "bower_components/underscore/underscore.js"
          "bower_components/backbone/backbone.js"
        ],
        after: [
          "vendor/*"
        ]

    stylesheets:
      defaultExtension: "scss"
      joinTo:
        'stylesheets/vendor.css': /^(vendor\/stylesheets|bower_components\/(?!foundation))/
        'stylesheets/app.css': /^app/

    templates:
      joinTo: 'javascripts/app.js'
  overrides:
    production:
      sourceMaps: true
      optimize: true
```
and the whole project actually: [inventaire-client](https://github.com/maxlath/inventaire-client/)

From what I can remember, when the bug started I was using brunch 1.8 and auto-reload-brunch 1.7.8, I tried to revert to older versions (brunch 1.7.20 and auto-reload-brunch 1.7.4) without success

my devDependencies
```
 "devDependencies": {
    "auto-reload-brunch": "^1.7.4",
    "brunch": "^1.7.20",
    "bower": "^1.4.1",
    "browserify": "^9.0.8",
    "chai": "^2.2.0",
    "clean-css-brunch": "^1.7.2",
    "coffee-script-brunch": "^1.8.1",
    "css-brunch": "^1.7.0",
    "git-digest-brunch": "^1.0.3",
    "graceful-fs": "^3.0.6",
    "handlebars": "^3.0.1",
    "handlebars-brunch": "^1.9.1",
    "html-minifier": "^0.7.2",
    "javascript-brunch": "^1.7.1",
    "ls": "^0.1.0",
    "mkdirp": "^0.5.0",
    "mocha": "^2.2.4",
    "sass-brunch": "^1.8.10",
    "sinon": "^1.14.1",
    "uglify-js-brunch": "^1.7.8"
  }
```

any idea of what could be happening? thanks in advance! :sos:
